name: Brandie
description: Brandie Task Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Utils
  device_info_plus: ^11.3.3
  intl: ^0.19.0
  flutter_screenutil: ^5.8.4
  flutter_easyloading: ^3.0.5
  logger: ^2.0.1

  # Network
  connectivity_plus: ^6.1.0
  cached_network_image: ^3.2.3
  http: ^1.2.0
  dio: ^5.3.2

  # Navigation & Notification
  url_launcher: ^6.1.12

  # Media (Image, Permission, Video)
  image_picker: ^1.1.2
  just_audio: ^0.9.46
  video_player: ^2.9.5
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.9
  #  cached_video_player_plus: ^2.0.0
  readmore: ^3.0.0
  flutter_cache_manager: ^3.3.1



  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Additional UI Elements (Toast, Popup, Addition Display)
  lottie: ^3.3.1
  fluttertoast: ^8.2.2
  flutter_animate: ^4.2.0+1
  timeago: ^3.6.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  rename: ^3.0.2

  package_info_plus: ^8.1.1




  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/audios/
    - assets/anim/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700


flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/images/splash_icon.png
  android: true
  ios: true
  color_dark: "#ffffff"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/splash_icon.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    image: assets/images/splash_icon.png

    # Splash screen background color.
    color: "#ffffff"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/images/splash_icon.png
    color_dark: "#ffffff"
    #icon_background_color_dark: "#eeeeee"
  fullscreen: true
